// Factory initial state for URX44V in Standard mode, captured from the device
// after a reset and used to seed a new plan (see defaultPlan). Values are the
// decoded plan-unit defaults the device ships with; the routing wires mirror its
// default input source / send / patch / ducker-key topology. Other models have no
// capture yet and start from an empty plan.

import type { NodeParams, PlanConnection } from "../core/plan";
import { SSMCS_INITIAL } from "../core/plan";

export const URX44V_NODE_PARAMS: Record<string, NodeParams> = {
  ch1: {
    on: true,
    gain: -8,
    hpf: false,
    hpfFreq: 80,
    phantom: false,
    clipSafe: false,
    compEqType: 0,
    phase: false,
    gateOn: false,
    compOn: false,
    eqOn: true,
    eqBands: [
      { on: true, q: 0.71, freq: 125, gain: 0, type: 1 },
      { on: true, q: 0.71, freq: 1000, gain: 0 },
      { on: true, q: 0.71, freq: 4000, gain: 0 },
      { on: true, q: 0.71, freq: 10000, gain: 0, type: 1 },
    ],
    gate: { threshold: -50, range: -56, attack: 20.17, hold: 15.3, decay: 150.2 },
    comp: { threshold: -18, ratio: 3, gain: 2, attack: 34.58, release: 218, knee: 1, autoMakeup: false, oneKnob: false, oneKnobLevel: 0 },
    ssmcs: SSMCS_INITIAL,
    insertFx: -1,
  },
  ch2: {
    on: true,
    gain: -8,
    hpf: false,
    hpfFreq: 80,
    phantom: false,
    clipSafe: false,
    compEqType: 0,
    phase: false,
    gateOn: false,
    compOn: false,
    eqOn: true,
    eqBands: [
      { on: true, q: 0.71, freq: 125, gain: 0, type: 1 },
      { on: true, q: 0.71, freq: 1000, gain: 0 },
      { on: true, q: 0.71, freq: 4000, gain: 0 },
      { on: true, q: 0.71, freq: 10000, gain: 0, type: 1 },
    ],
    gate: { threshold: -50, range: -56, attack: 20.17, hold: 15.3, decay: 150.2 },
    comp: { threshold: -18, ratio: 3, gain: 2, attack: 34.58, release: 218, knee: 1, autoMakeup: false, oneKnob: false, oneKnobLevel: 0 },
    ssmcs: SSMCS_INITIAL,
    insertFx: -1,
  },
  ch3: {
    on: true,
    gain: -8,
    hpf: false,
    hpfFreq: 80,
    phantom: false,
    clipSafe: false,
    hiZ: false,
    compEqType: 0,
    phase: false,
    gateOn: false,
    compOn: false,
    eqOn: true,
    eqBands: [
      { on: true, q: 0.71, freq: 125, gain: 0, type: 1 },
      { on: true, q: 0.71, freq: 1000, gain: 0 },
      { on: true, q: 0.71, freq: 4000, gain: 0 },
      { on: true, q: 0.71, freq: 10000, gain: 0, type: 1 },
    ],
    gate: { threshold: -50, range: -56, attack: 20.17, hold: 15.3, decay: 150.2 },
    comp: { threshold: -18, ratio: 3, gain: 2, attack: 34.58, release: 218, knee: 1, autoMakeup: false, oneKnob: false, oneKnobLevel: 0 },
    ssmcs: SSMCS_INITIAL,
    insertFx: -1,
  },
  ch4: {
    on: true,
    gain: -8,
    hpf: false,
    hpfFreq: 80,
    phantom: false,
    clipSafe: false,
    hiZ: false,
    compEqType: 0,
    phase: false,
    gateOn: false,
    compOn: false,
    eqOn: true,
    eqBands: [
      { on: true, q: 0.71, freq: 125, gain: 0, type: 1 },
      { on: true, q: 0.71, freq: 1000, gain: 0 },
      { on: true, q: 0.71, freq: 4000, gain: 0 },
      { on: true, q: 0.71, freq: 10000, gain: 0, type: 1 },
    ],
    gate: { threshold: -50, range: -56, attack: 20.17, hold: 15.3, decay: 150.2 },
    comp: { threshold: -18, ratio: 3, gain: 2, attack: 34.58, release: 218, knee: 1, autoMakeup: false, oneKnob: false, oneKnobLevel: 0 },
    ssmcs: SSMCS_INITIAL,
    insertFx: -1,
  },
  ch_5_6: {
    on: true,
    gain: 0,
    phaseL: false,
    phaseR: false,
    eqOn: true,
    eqBands: [
      { on: true, q: 0.71, freq: 125, gain: 0, type: 1 },
      { on: true, q: 0.71, freq: 1000, gain: 0 },
      { on: true, q: 0.71, freq: 4000, gain: 0 },
      { on: true, q: 0.71, freq: 10000, gain: 0, type: 1 },
    ],
  },
  ch_7_8: {
    on: true,
    gain: -14,
    phaseL: false,
    phaseR: false,
    eqOn: true,
    eqBands: [
      { on: true, q: 0.71, freq: 125, gain: 0, type: 1 },
      { on: true, q: 0.71, freq: 1000, gain: 0 },
      { on: true, q: 0.71, freq: 4000, gain: 0 },
      { on: true, q: 0.71, freq: 10000, gain: 0, type: 1 },
    ],
  },
  ch_9_10: {
    on: true,
    gain: 0,
    phaseL: false,
    phaseR: false,
    eqOn: true,
    eqBands: [
      { on: true, q: 0.71, freq: 125, gain: 0, type: 1 },
      { on: true, q: 0.71, freq: 1000, gain: 0 },
      { on: true, q: 0.71, freq: 4000, gain: 0 },
      { on: true, q: 0.71, freq: 10000, gain: 0, type: 1 },
    ],
  },
  ch_11_12: {
    on: true,
    gain: -14,
    phaseL: false,
    phaseR: false,
    eqOn: true,
    eqBands: [
      { on: true, q: 0.71, freq: 125, gain: 0, type: 1 },
      { on: true, q: 0.71, freq: 1000, gain: 0 },
      { on: true, q: 0.71, freq: 4000, gain: 0 },
      { on: true, q: 0.71, freq: 10000, gain: 0, type: 1 },
    ],
  },
  "bus.stereo": {
    level: 0,
    insertFx: -1,
    eqOn: true,
    eqBands: [
      { on: true, q: 0.71, freq: 125, gain: 0, type: 1 },
      { on: true, q: 0.71, freq: 1000, gain: 0 },
      { on: true, q: 0.71, freq: 4000, gain: 0 },
      { on: true, q: 0.71, freq: 10000, gain: 0, type: 1 },
    ],
    on: true,
  },
  "bus.mix1": {
    level: 0,
    insertFx: -1,
    eqOn: true,
    eqBands: [
      { on: true, q: 0.71, freq: 125, gain: 0, type: 1 },
      { on: true, q: 0.71, freq: 1000, gain: 0 },
      { on: true, q: 0.71, freq: 4000, gain: 0 },
      { on: true, q: 0.71, freq: 10000, gain: 0, type: 1 },
    ],
  },
  "bus.mix2": {
    level: 0,
    insertFx: -1,
    eqOn: true,
    eqBands: [
      { on: true, q: 0.71, freq: 125, gain: 0, type: 1 },
      { on: true, q: 0.71, freq: 1000, gain: 0 },
      { on: true, q: 0.71, freq: 4000, gain: 0 },
      { on: true, q: 0.71, freq: 10000, gain: 0, type: 1 },
    ],
  },
  "out.ducker1": {
    duckerOn: false,
    ducker: { threshold: -40, range: -24, attack: 20.17, decay: 1000 },
  },
  "out.ducker2": {
    duckerOn: false,
    ducker: { threshold: -40, range: -24, attack: 20.17, decay: 1000 },
  },
  "out.ducker3": {
    duckerOn: false,
    ducker: { threshold: -40, range: -24, attack: 20.17, decay: 1000 },
  },
  "out.ducker4": {
    duckerOn: false,
    ducker: { threshold: -40, range: -24, attack: 20.17, decay: 1000 },
  },
  "bus.mon1": { level: 0, cueInterrupt: true, mono: false },
  "bus.mon2": { level: 0, cueInterrupt: true, mono: false },
  "bus.osc": {
    osc: { on: false, level: -14, mode: 0, freq: 1000 },
  },
  // STREAMING DELAY factory state, read from the device: off, 1.00 ms, 30 fps.
  // Seeded so writing a fresh plan restores the device's delay (the absolute
  // write only auto-clears wires, not scalar node params — see bus.osc/monitor).
  "bus.stream": { delay: { on: false, time: 1, frameRate: 5 } },
};

// Factory CH SETTING colors, read from the device: input channels and the FX
// buses ship Blue, the MIX and STREAMING buses Orange, the STEREO master Red. Hex
// are the COLOR_PALETTE entries (Blue = index 0, Orange = 1, Red = 6); kept as
// literals so this data file does not depend on the control layer.
export const URX44V_NODE_COLORS: Record<string, string> = {
  ch1: "#4a78c0",
  ch2: "#4a78c0",
  ch3: "#4a78c0",
  ch4: "#4a78c0",
  ch_5_6: "#4a78c0",
  ch_7_8: "#4a78c0",
  ch_9_10: "#4a78c0",
  ch_11_12: "#4a78c0",
  "bus.fx1": "#4a78c0",
  "bus.fx2": "#4a78c0",
  "bus.mix1": "#e8913a",
  "bus.mix2": "#e8913a",
  "bus.stream": "#e8913a",
  "bus.stereo": "#d9534f",
};

// Factory CH SETTING names, read from the device (mono channels from param 18,
// stereo channels from param 206, buses from their own params), trimmed to match
// readback. Mono ship "ch 1".."ch 4", stereo the pair label "5/ 6"…, buses their
// short labels.
export const URX44V_NODE_NAMES: Record<string, string> = {
  ch1: "ch 1",
  ch2: "ch 2",
  ch3: "ch 3",
  ch4: "ch 4",
  ch_5_6: "5/ 6",
  ch_7_8: "7/ 8",
  ch_9_10: "9/10",
  ch_11_12: "11/12",
  "bus.fx1": "FX 1",
  "bus.fx2": "FX 2",
  "bus.mix1": "MIX1",
  "bus.mix2": "MIX2",
  "bus.stream": "Strm",
  "bus.stereo": "ST",
};

export const URX44V_CONNECTIONS: PlanConnection[] = [
  {
    from: "ch1:out",
    to: "bus.stereo:in",
    kind: "send",
    params: { level: 0, pan: 0 },
  },
  {
    from: "ch2:out",
    to: "bus.stereo:in",
    kind: "send",
    params: { level: 0, pan: 0 },
  },
  {
    from: "ch3:out",
    to: "bus.stereo:in",
    kind: "send",
    params: { level: 0, pan: 0 },
  },
  {
    from: "ch4:out",
    to: "bus.stereo:in",
    kind: "send",
    params: { level: 0, pan: 0 },
  },
  {
    from: "ch_5_6:out",
    to: "bus.stereo:in",
    kind: "send",
    params: { level: 0, pan: 0 },
  },
  {
    from: "ch_7_8:out",
    to: "bus.stereo:in",
    kind: "send",
    params: { level: 0, pan: 0 },
  },
  {
    from: "ch_9_10:out",
    to: "bus.stereo:in",
    kind: "send",
    params: { level: 0, pan: 0 },
  },
  {
    from: "ch_11_12:out",
    to: "bus.stereo:in",
    kind: "send",
    params: { level: 0, pan: 0 },
  },
  {
    from: "bus.fx1:out",
    to: "bus.stereo:in",
    kind: "send",
    params: { level: -96.5 },
  },
  {
    from: "bus.fx2:out",
    to: "bus.stereo:in",
    kind: "send",
    params: { level: -96.5 },
  },
  {
    from: "ch1:out",
    to: "bus.mix1:in",
    kind: "send",
    params: { level: -96.5, pan: 0, tap: "post" },
  },
  {
    from: "ch1:out",
    to: "bus.mix2:in",
    kind: "send",
    params: { level: -96.5, pan: 0, tap: "post" },
  },
  {
    from: "ch1:out",
    to: "bus.fx1:in",
    kind: "send",
    params: { level: -96.5, tap: "post" },
  },
  {
    from: "ch1:out",
    to: "bus.fx2:in",
    kind: "send",
    params: { level: -96.5, tap: "post" },
  },
  {
    from: "ch2:out",
    to: "bus.mix1:in",
    kind: "send",
    params: { level: -96.5, pan: 0, tap: "post" },
  },
  {
    from: "ch2:out",
    to: "bus.mix2:in",
    kind: "send",
    params: { level: -96.5, pan: 0, tap: "post" },
  },
  {
    from: "ch2:out",
    to: "bus.fx1:in",
    kind: "send",
    params: { level: -96.5, tap: "post" },
  },
  {
    from: "ch2:out",
    to: "bus.fx2:in",
    kind: "send",
    params: { level: -96.5, tap: "post" },
  },
  {
    from: "ch3:out",
    to: "bus.mix1:in",
    kind: "send",
    params: { level: -96.5, pan: 0, tap: "post" },
  },
  {
    from: "ch3:out",
    to: "bus.mix2:in",
    kind: "send",
    params: { level: -96.5, pan: 0, tap: "post" },
  },
  {
    from: "ch3:out",
    to: "bus.fx1:in",
    kind: "send",
    params: { level: -96.5, tap: "post" },
  },
  {
    from: "ch3:out",
    to: "bus.fx2:in",
    kind: "send",
    params: { level: -96.5, tap: "post" },
  },
  {
    from: "ch4:out",
    to: "bus.mix1:in",
    kind: "send",
    params: { level: -96.5, pan: 0, tap: "post" },
  },
  {
    from: "ch4:out",
    to: "bus.mix2:in",
    kind: "send",
    params: { level: -96.5, pan: 0, tap: "post" },
  },
  {
    from: "ch4:out",
    to: "bus.fx1:in",
    kind: "send",
    params: { level: -96.5, tap: "post" },
  },
  {
    from: "ch4:out",
    to: "bus.fx2:in",
    kind: "send",
    params: { level: -96.5, tap: "post" },
  },
  {
    from: "ch_5_6:out",
    to: "bus.mix1:in",
    kind: "send",
    params: { level: -96.5, pan: 0, tap: "post" },
  },
  {
    from: "ch_5_6:out",
    to: "bus.mix2:in",
    kind: "send",
    params: { level: -96.5, pan: 0, tap: "post" },
  },
  {
    from: "ch_5_6:out",
    to: "bus.fx1:in",
    kind: "send",
    params: { level: -96.5, tap: "post" },
  },
  {
    from: "ch_5_6:out",
    to: "bus.fx2:in",
    kind: "send",
    params: { level: -96.5, tap: "post" },
  },
  {
    from: "ch_7_8:out",
    to: "bus.mix1:in",
    kind: "send",
    params: { level: -96.5, pan: 0, tap: "post" },
  },
  {
    from: "ch_7_8:out",
    to: "bus.mix2:in",
    kind: "send",
    params: { level: -96.5, pan: 0, tap: "post" },
  },
  {
    from: "ch_7_8:out",
    to: "bus.fx1:in",
    kind: "send",
    params: { level: -96.5, tap: "post" },
  },
  {
    from: "ch_7_8:out",
    to: "bus.fx2:in",
    kind: "send",
    params: { level: -96.5, tap: "post" },
  },
  {
    from: "ch_9_10:out",
    to: "bus.mix1:in",
    kind: "send",
    params: { level: -96.5, pan: 0, tap: "post" },
  },
  {
    from: "ch_9_10:out",
    to: "bus.mix2:in",
    kind: "send",
    params: { level: -96.5, pan: 0, tap: "post" },
  },
  {
    from: "ch_9_10:out",
    to: "bus.fx1:in",
    kind: "send",
    params: { level: -96.5, tap: "post" },
  },
  {
    from: "ch_9_10:out",
    to: "bus.fx2:in",
    kind: "send",
    params: { level: -96.5, tap: "post" },
  },
  {
    from: "ch_11_12:out",
    to: "bus.mix1:in",
    kind: "send",
    params: { level: -96.5, pan: 0, tap: "post" },
  },
  {
    from: "ch_11_12:out",
    to: "bus.mix2:in",
    kind: "send",
    params: { level: -96.5, pan: 0, tap: "post" },
  },
  {
    from: "ch_11_12:out",
    to: "bus.fx1:in",
    kind: "send",
    params: { level: -96.5, tap: "post" },
  },
  {
    from: "ch_11_12:out",
    to: "bus.fx2:in",
    kind: "send",
    params: { level: -96.5, tap: "post" },
  },
  { from: "ch1:out", to: "out.ducker1:in", kind: "key" },
  { from: "ch1:out", to: "out.ducker2:in", kind: "key" },
  { from: "ch1:out", to: "out.ducker3:in", kind: "key" },
  { from: "ch1:out", to: "out.ducker4:in", kind: "key" },
  {
    from: "bus.osc:out",
    to: "bus.stereo:in",
    kind: "sendSwitch",
    params: { oscL: true, oscR: true },
  },
  { from: "in.micline_1_2:out", to: "ch1:in", kind: "source" },
  { from: "in.micline_1_2:out", to: "ch2:in", kind: "source" },
  { from: "in.micline_3_4:out", to: "ch3:in", kind: "source" },
  { from: "in.micline_3_4:out", to: "ch4:in", kind: "source" },
  { from: "bus.stereo:out", to: "bus.stream:in", kind: "source" },
  { from: "bus.stereo:out", to: "out.usbmain_a:in", kind: "patch" },
  { from: "bus.stereo:out", to: "out.usbmain_b:in", kind: "patch" },
  { from: "bus.stereo:out", to: "out.usbmain_c:in", kind: "patch" },
  { from: "bus.stereo:out", to: "out.usbsub:in", kind: "patch" },
  { from: "bus.stereo:out", to: "bus.mon1:in", kind: "source" },
  { from: "bus.stereo:out", to: "bus.mon2:in", kind: "source" },
  { from: "bus.stereo:out", to: "out.main:in", kind: "patch" },
  { from: "bus.mix1:out", to: "out.line:in", kind: "patch" },
];
